export const mockCategories = [
  {
    id: 1,
    name: "Electronics",
    slug: "electronics",
    description:
      "Devices and gadgets for everyday use, including smartphones, laptops, and accessories.",
    parentId: null,
    featured: true,
    productCount: 42,
  },
  {
    id: 2,
    name: "Smartphones",
    slug: "smartphones",
    description: "Latest mobile phones and accessories from top brands.",
    parentId: 1,
    featured: false,
    productCount: 18,
  },
  {
    id: 3,
    name: "Laptops",
    slug: "laptops",
    description: "Powerful laptops for work, gaming, and everyday use.",
    parentId: 1,
    featured: false,
    productCount: 15,
  },
  {
    id: 4,
    name: "Audio",
    slug: "audio",
    description: "Headphones, earbuds, and speakers for premium sound quality.",
    parentId: 1,
    featured: false,
    productCount: 9,
  },
  {
    id: 5,
    name: "Fashion",
    slug: "fashion",
    description:
      "Clothing, shoes, and accessories for men, women, and children.",
    parentId: null,
    featured: true,
    productCount: 56,
  },
  {
    id: 6,
    name: "Men's Clothing",
    slug: "mens-clothing",
    description: "Shirts, pants, jackets, and more for men.",
    parentId: 5,
    featured: false,
    productCount: 22,
  },
  {
    id: 7,
    name: "Women's Clothing",
    slug: "womens-clothing",
    description: "Dresses, tops, skirts, and more for women.",
    parentId: 5,
    featured: false,
    productCount: 28,
  },
  {
    id: 8,
    name: "Accessories",
    slug: "accessories",
    description: "Watches, bags, jewelry, and other fashion accessories.",
    parentId: 5,
    featured: false,
    productCount: 6,
  },
  {
    id: 9,
    name: "Home & Kitchen",
    slug: "home-kitchen",
    description: "Furniture, appliances, and decor for your home.",
    parentId: null,
    featured: false,
    productCount: 37,
  },
  {
    id: 10,
    name: "Furniture",
    slug: "furniture",
    description: "Sofas, tables, chairs, and more for every room.",
    parentId: 9,
    featured: false,
    productCount: 12,
  },
  {
    id: 11,
    name: "Kitchen Appliances",
    slug: "kitchen-appliances",
    description:
      "Blenders, mixers, coffee makers, and other kitchen essentials.",
    parentId: 9,
    featured: false,
    productCount: 15,
  },
  {
    id: 12,
    name: "Home Decor",
    slug: "home-decor",
    description: "Decorative items to beautify your living space.",
    parentId: 9,
    featured: false,
    productCount: 10,
  },
];
